language: csharp
solution: PyXel.sln

matrix:
  include:
    - os: linux # Ubuntu 14.04
      sudo: required
      dotnet: 2.1.4
    - os: osx # OSX 10.12
      osx_image: xcode7.3
      dotnet: 2.1.4

## If `dotnet` configuration doesnt work, use install script instead
# install:
#  - export DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
#  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
#  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
